#ifndef LWM2M_LITTLE_ENDIAN
    #if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
    #define LWM2M_LITTLE_ENDIAN
    #endif
#endif
#define LWM2M_CLIENT_MODE 1
#define LWM2M_FIRMWARE_UPGRADES 1
#define POSIX 1
#define LWM2M_SUPPORT_JSON 1
#define LWM2M_WITH_LOGS 1
